# Generated by Django 5.2.1 on 2025-06-04 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versionsheets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versionsheet',
            name='formatted_issuance_date',
        ),
        migrations.AlterField(
            model_name='versionsheet',
            name='issuance_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
