# Generated by Django 5.2.1 on 2025-06-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versionsheets', '0002_remove_versionsheet_formatted_issuance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionsheet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
