version: "3.9"

services:
  web:
    build: .
    container_name: gmi_dummy_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - pg
    networks:
      - backend_pg

networks:
  backend_pg:
    external: true
