# Generated by Django 5.2.1 on 2025-06-04 09:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('published', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=100)),
                ('shape_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dpi', models.CharField(max_length=10)),
                ('num', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('width', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('pdf_url', models.URLField()),
                ('page_index', models.IntegerField(default=0)),
                ('plan_set_id', models.UUIDField()),
                ('full_img_url', models.URLField()),
                ('version_set_id', models.UUIDField()),
                ('plan_set_s3_url', models.URLField()),
                ('thumbnail_url', models.URLField()),
                ('plan_set_filename', models.CharField(max_length=255)),
                ('text_extract_data_url', models.URLField()),
                ('text_detect_full_page_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='projects.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_sheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
