# Generated by Django 5.2.1 on 2025-06-04 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('sheets', '0001_initial'),
        ('versionsheets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='version_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='versionsheets.versionsheet'),
        ),
        migrations.AddField(
            model_name='sheetannotation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheetannotations', to='projects.project'),
        ),
        migrations.AddField(
            model_name='sheetannotation',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheetannotations', to='sheets.sheet'),
        ),
        migrations.AddField(
            model_name='sheetannotation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
