# Generated by Django 5.2.1 on 2025-06-04 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('published', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=100)),
                ('shape_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('raw_url', models.URLField()),
                ('default_url', models.URLField()),
                ('large_url', models.URLField()),
                ('thumbnail_url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('tmp_uri', models.CharField(blank=True, max_length=500, null=True)),
                ('filename', models.CharField(max_length=255)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_temporarily_present', models.BooleanField(default=False)),
                ('is_annotation', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='projects.project')),
            ],
        ),
    ]
