# Generated by Django 5.2.1 on 2025-06-04 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='Key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sign',
            name='rawUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sign',
            name='thumbnailUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sign',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sign',
            name='file_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
