# Generated by Django 5.2.2 on 2025-06-05 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_sign_key_sign_rawurl_sign_thumbnailurl_sign_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_signatures', to=settings.AUTH_USER_MODEL),
        ),
    ]
